MAKEFILE_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

RUN_TAG = $(shell ls librelane/runs/ | tail -n 1)
TOP = chip_top

PDK_ROOT ?= $(MAKEFILE_DIR)/gf180mcu
PDK ?= gf180mcuD
PDK_COMMIT ?= 9233c19260cd813c3fa67dd4594fe4cc67016832

# SlugTPU configuration
SCL  ?= gf180mcu_as_sc_mcu7t3v3
PAD  ?= gf180mcu_fd_io
SRAM ?= gf180mcu_ocd_ip_sram

# Available SCL libraries:
# gf180mcu_as_sc_mcu7t3v3
# gf180mcu_fd_sc_mcu7t5v0
# gf180mcu_fd_sc_mcu9t5v0
# gf180mcu_osu_sc_gp9t3v3 (broken)
# gf180mcu_osu_sc_gp12t3v3 (broken)

ifeq ($(SCL),default)
    SCL = gf180mcu_fd_sc_mcu7t5v0
endif
SCL ?= gf180mcu_fd_sc_mcu7t5v0

# Available PAD libraries:
# gf180mcu_fd_io
# gf180mcu_ocd_io

ifeq ($(PAD),default)
    PAD = gf180mcu_fd_io
endif
PAD ?= gf180mcu_fd_io

# Available SRAM macros:
# gf180mcu_fd_ip_sram
# gf180mcu_ocd_ip_sram

ifeq ($(SRAM),default)
    SRAM = gf180mcu_fd_ip_sram
endif
SRAM ?= gf180mcu_fd_ip_sram

ifeq ($(SRAM),gf180mcu_fd_ip_sram)
    MACROS = 5v
else
    MACROS = 3v3
endif

AVAILABLE_SLOTS = 1x1 0p5x1 1x0p5 0p5x0p5
DEFAULT_SLOT = 1x1

# always dump waveforms
export WAVES=1
RTL_FILES := $(shell find src/ -name "*.sv")

# Slot can be any of AVAILABLE_SLOTS
SLOT ?= $(DEFAULT_SLOT)

ifeq ($(SLOT),default)        
    SLOT = $(DEFAULT_SLOT)
endif

ifeq ($(filter $(SLOT),$(AVAILABLE_SLOTS)),)
    $(error $(SLOT) does not exist in AVAILABLE_SLOTS: $(AVAILABLE_SLOTS))
endif

SLOT_DEFINE = SLOT_$(shell echo $(SLOT) | tr '[:lower:]' '[:upper:]')
SRAM_DEFINE = SRAM_$(SRAM)

LIBRELANE_OPTS = --pdk ${PDK} --pdk-root ${PDK_ROOT} --manual-pdk --scl ${SCL} --pad ${PAD}
LIBRELANE_CONFIGS = librelane/slots/slot_${SLOT}.yaml librelane/macros/macros_${MACROS}.yaml librelane/config.yaml

.DEFAULT_GOAL := help

help: ## Show this help message
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Available targets:'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-20s %s\n", $$1, $$2}'
.PHONY: help

all: librelane ## Build the project (runs LibreLane)
.PHONY: all

$(PDK_ROOT)/ciel/gf180mcu/versions/$(PDK_COMMIT)/$(PDK):
	ciel enable $(PDK_COMMIT) --pdk-root $(PDK_ROOT) --pdk-family $(PDK) --include-libraries all

clone-pdk: $(PDK_ROOT)/ciel/gf180mcu/versions/$(PDK_COMMIT)/$(PDK) ## Clone the gf180mcu PDK
.PHONY: clone-pdk

# Need to find a better way to
# pass the variables to LibreLane
defines:
	@echo "Writing src/generated_defines.svh"
	$(file >src/generated_defines.svh,// This file is auto-generated by the Makefile)
	$(file >>src/generated_defines.svh,`define ${SLOT_DEFINE})
	$(file >>src/generated_defines.svh,`define ${SRAM_DEFINE})
.PHONY: defines

librelane: clone-pdk defines ## Run LibreLane flow (synthesis, PnR, verification)
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final
.PHONY: librelane

librelane-condensed: clone-pdk defines ## Run LibreLane flow (synthesis, PnR, verification)
	SRAM_DEFINE=${SRAM_DEFINE} librelane --condensed ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final
.PHONY: librelane-condensed

librelane-nodrc: clone-pdk defines ## Run LibreLane flow without DRC checks
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final --skip KLayout.Antenna --skip KLayout.DRC --skip Magic.DRC
.PHONY: librelane-nodrc

librelane-klayoutdrc: clone-pdk defines ## Run LibreLane flow without magic DRC checks
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final --skip Magic.DRC
.PHONY: librelane-klayoutdrc

librelane-magicdrc: clone-pdk defines ## Run LibreLane flow without KLayout DRC checks
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final --skip KLayout.DRC
.PHONY: librelane-magicdrc

librelane-openroad: clone-pdk defines ## Open the last run in OpenROAD
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --last-run --flow OpenInOpenROAD
.PHONY: librelane-openroad

librelane-klayout: clone-pdk defines ## Open the last run in KLayout
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --last-run --flow OpenInKLayout
.PHONY: librelane-klayout

librelane-padring: clone-pdk defines ## Only create the padring
	python3 scripts/padring.py ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS}
.PHONY: librelane-padring

#lint-tpu-soc: 
#	librelane librelane/slots/slot_1x1.yaml librelane/config.yaml \
#                  --pdk gf180mcuD --pdk-root ${PDK_ROOT} --manual-pdk \
#                  --to Checker.LintWarnings
#.PHONY: lint-tpu-soc
sim: clone-pdk defines ## Run RTL simulation with cocotb
	PDK_ROOT=${PDK_ROOT} PDK=${PDK} SLOT=${SLOT} PAD=${PAD} SCL=${SCL} SRAM=${SRAM} python3 -m pytest cocotb/test_chip_top.py
.PHONY: sim

sim-gl: clone-pdk defines ## Run gate-level simulation with cocotb (after copy-final)
	GL=1 PDK_ROOT=${PDK_ROOT} PDK=${PDK} SLOT=${SLOT} PAD=${PAD} SCL=${SCL} SRAM=${SRAM} python3 -m pytest cocotb/test_chip_top.py
.PHONY: sim-gl

sim-fifo:
	python3 -m pytest cocotb/test_fifo.py -s

sim-spi:
	python3 -m pytest cocotb/test_spi.py -s

sim-scalar-load:
	python3 -m pytest cocotb/test_load_data.py -s

sim-scalar-pipe:
	python3 -m pytest cocotb/test_scalar_pipe.py -s

sim-scalar-stage:
	python3 -m pytest cocotb/test_scalar_stage.py -s

sim-add-n:
	python3 -m pytest cocotb/test_add_n.py -s

sim-relu-n:
	python3 -m pytest cocotb/test_relu_n.py -s

sim-scale-n:
	python3 -m pytest cocotb/test_scale_n.py -s

sim-sram:
	python3 -m pytest cocotb/test_sram.py -s

sim-tri:
	python3 -m pytest cocotb/test_tri.py -s

sim-sysray-nxn:
	python3 -m pytest cocotb/test_sysray_nxn.py -s

sim-activation-sram:
	python3 -m pytest cocotb/test_activation_sram.py -s

sim-scalar-stage-sram:
	python3 -m pytest cocotb/test_scalar_stage_sram.py -s

sim-compute-core:
	python3 -m pytest cocotb/test_compute_core.py -s

sim-mxu:
	python3 -m pytest cocotb/test_mxu.py -s

sim-regs:
	python3 -m pytest cocotb/test_tpu_regs.py -s

sim-wb-mux:
	python3 -m pytest cocotb/test_wb_mux.py -s

sim-wb-dma:
	python3 -m pytest cocotb/test_wb_dma.py -s

sim-wb-dma-sdram:
	python3 -m pytest cocotb/test_wb_dma_sdram.py -s

sim-spibone-dram:
	python3 -m pytest cocotb/test_spibone_dram.py -s

sim-control-buffer:
	python3 -m pytest cocotb/test_control_buffer.py -s

sim-control-sram:
	python3 -m pytest cocotb/test_control_sram.py -s

sim-control-decoder:
	python3 -m pytest cocotb/test_control_decoder.py -s

sim-control-top:
	python3 -m pytest cocotb/test_control_top.py -s

sim-wb-sdr-mt48lc16m16a2:
	python3 -m pytest cocotb/test_wb_sdr_mt48lc16m16a2_7e.py -s

sim-tpu-soc-with-dram:
	python3 -m pytest cocotb/test_tpu_soc_with_dram.py -s

sim-tpu-instructions:
	python3 -m pytest cocotb/test_tpu_instructions.py -s

sim-general-test-example: clone-pdk defines
	PDK_ROOT=${PDK_ROOT} PDK=${PDK} SLOT=${SLOT} PAD=${PAD} SCL=${SCL} SRAM=${SRAM} python3 -m pytest cocotb/general_test/test_tpu_workload.py -s -v \
	--tpu-bin     	 cocotb/general_test/single_layer_8x8_test/test.bin \
	--tpu-dram-init  cocotb/general_test/single_layer_8x8_test/input_data.toml  \
	--tpu-expected   cocotb/general_test/single_layer_8x8_test/expected.toml   \
	--tpu-pc         0x1                  \
	--tpu-post-cycles 2000                \
	--tpu-timeout-mult 1.5 

sim-general-8x16: clone-pdk defines
	PDK_ROOT=${PDK_ROOT} PDK=${PDK} SLOT=${SLOT} PAD=${PAD} SCL=${SCL} SRAM=${SRAM} python3 -m pytest cocotb/general_test/test_tpu_workload.py -s -v \
	--tpu-bin     	 cocotb/general_test/single_layer_8x16/inst.bin \
	--tpu-dram-init  cocotb/general_test/single_layer_8x16/input_data.toml  \
	--tpu-expected   cocotb/general_test/single_layer_8x16/expected.toml   \
	--tpu-pc         0x1                  \
	--tpu-post-cycles 2000                \
	--tpu-timeout-mult 1.5    

sim-general-8x24: clone-pdk defines
	PDK_ROOT=${PDK_ROOT} PDK=${PDK} SLOT=${SLOT} PAD=${PAD} SCL=${SCL} SRAM=${SRAM} python3 -m pytest cocotb/general_test/test_tpu_workload.py -s -v \
	--tpu-bin     	 cocotb/general_test/single_layer_8x16/inst.bin \
	--tpu-dram-init  cocotb/general_test/single_layer_8x16/input_data.toml  \
	--tpu-expected   cocotb/general_test/single_layer_8x16/expected.toml   \
	--tpu-pc         0x1                  \
	--tpu-post-cycles 2000                \
	--tpu-timeout-mult 1.5                          

#sim-view: ## View simulation waveforms in GTKWave
#	gtkwave cocotb/sim_build/chip_top.fst
.PHONY: sim-view
